### ISSUE TITLE
Workflow doesn't trigger on labeled pull request

### ISSUE THREAD

**Issue by jgonggrijp** [devmasx/merge-branch#11]
This may or may not be an issue with the merge-branch action; I thought I'd try here before contacting GitHub.

I'm trying to set up a workflow where, when the "ready to launch" label is set on a pull request for a `release/*` branch, the branch in question is merged into another branch called `prepublish`. This workflow is defined [here](https://github.com/documentcloud/underscore-contrib/blob/master/.github/workflows/prepublish.yml). It was inspired on [the documentation](https://github.com/marketplace/actions/merge-branch).

I have made three failed attempts at triggering this workflow:

1. https://github.com/documentcloud/underscore-contrib/pull/235 (workflow wasn't on `master` yet)
2. https://github.com/documentcloud/underscore-contrib/pull/237 (branch was on my fork)
3. https://github.com/documentcloud/underscore-contrib/pull/238 (branch on upstream repo, can't explain failure to trigger)

Either I'm misunderstanding how to do this, or something doesn't work as advertised in merge-branch or in the GH Actions API. Can you help me? Thanks in advance!

**Comment by MiguelSavignano** [comment]
Hello @jgonggrijp, thanks for the issue.

I have done some tests, the event never fires the workflow, it seems that the labeled event in a pull request does not allow filtering branches. Without the branch filter should be work.

Example:
```yaml
name: Prepublication staging

on:
  pull_request:
    types: [labeled]
    # branches:
    #   - release/*
    #  - hotfix/*

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge into prepublish
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: ready to launch
          target_branch: prepublish
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

I will try to investigate a little more because it does not work with the branch filter, However, using conditions in the job should be work.

Example:
```yaml
name: Prepublication staging

on:
  pull_request:
    types: [labeled]

jobs:
  stage:
    if: contains(github.ref, 'refs/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge into prepublish
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: ready to launch
          target_branch: prepublish
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
