### ISSUE TITLE
[Question] Automatic merge from "release/*" to "master"

### ISSUE THREAD

**Issue by jeffchew** [devmasx/merge-branch#2]
I'm interested in setting up a flow where any changes (pushes or merged pull requests) to a release branch (`release/*`) gets automatically merged down to `master`, and looks like your action might be able to help with that. Would a configuration like this work?

```
name: Merge release branch to master
on:
  push:
    branches:
      - 'release/*'
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to master
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
