### ISSUE TITLE
Merge commit no longer has a message

### ISSUE THREAD

**Issue by grimsa** [devmasx/merge-branch#23]
I ran into an issue that seems to be a combination of two factors:
1. In my GitHub Action I have to depend on a `master` version, because depending on a stable version is not possible (https://github.com/devmasx/merge-branch/issues/16)
2. `master` branch had a breaking change introduced with this new feature: https://github.com/devmasx/merge-branch/issues/18

Step config in my case:
```
      - name: Merge develop -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: staging
          github_token: ${{ secrets.LYRA_REPO_ACCESS_TOKEN }}
```
Previously (e.g. on 2021-10-27) this resulted in a commit with a message `Merge develop into staging`.
Today (2021-11-02) this resulted in an empty commit message.
There was no change in configuration.

So I think these are really two issues:
1. There is no stable release to depend on (https://github.com/devmasx/merge-branch/issues/16)
2. The newly added optional commit message is not really optional

**Comment by dominicarrojado** [comment]
I guess "optional" here is correct, just that there's no default one, you could add your own commit message like this instead:

```
      - name: Merge develop -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: 'merge develop into main'
          target_branch: main
          github_token: ${{ github.token }}
```
