### ISSUE TITLE
delete merged branch?

### ISSUE THREAD

**Issue by utkarshsethi** [devmasx/merge-branch#27]
Is there a way to also delete the merged branch?

I've tried looking at the API, but can't seem to find a way to do it. [might also be simply in-experienced]

This will allow total automation of some tasks instead of having to delete merged branches later.

**Comment by utkarshsethi** [comment]
Found the solution.
For anyone's future reference:

For a specific repo can be enabled in settings. as follows:
![image](https://user-images.githubusercontent.com/2989912/147206276-2090fa9c-a7d8-4b67-9911-b2b79f539179.png)

Or I created a simple workflow using gh cli:

```
      - uses: actions/checkout@master

        #merge and delete
      - name: Auto Merge license -> master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh pr checkout license
          gh pr merge -d -m
```
