### ISSUE TITLE
merge silently skiped

### ISSUE THREAD

**Issue by auto-eric** [devmasx/merge-branch#33]
I have included this step into my job
```
    steps:
      - uses: actions/checkout@v3

      - name: Merge ${{ env.SOURCE_BRANCH }} -> ${{ env.TARGET_BRANCH }}
        uses: devmasx/merge-branch@master
        with:
          target_branch: ${{ env.TARGET_BRANCH }}
          github_token: ${{ secrets.GIT_PRIVATE_TOKEN }}
```
The message is `Neutral: skip merge target_branch: staging @head_to_merge: 64cea87bb4409975f4759c985f0ff59ec22bc1f3`.

I would expect
* fail if merge is skipped
* feedback why it is skiped
