### ISSUE TITLE
Feature: Ability to replace a branch instead of merge

### ISSUE THREAD

**Issue by TSMMark** [devmasx/merge-branch#37]
Thanks for this awesome gh action. Been using it for years now

---

I have a new workflow idea and I want to force push / replace another branch with the current branch. (rather than merge into)

It seems pretty close to the current API so I thought maybe it could just be another option, e.g.

```yaml
- name: deploy/stage-a
  uses: devmasx/merge-branch@v1.3.1
  with:
    label_name: 'deploy stage-a'
    from_branch: ${{ env.GITHUB_HEAD_REF_SLUG }}
    target_branch: 'deploy/stage-a'
    github_token: ${{ github.token }}
    replace: true
```

Thoughts on what it would take to implement this? Could it be accepted?
