### ISSUE TITLE
on push does not trigger on the target branch

### ISSUE THREAD

**Issue by AurimasNav** [devmasx/merge-branch#42]
Not sure if this is specific to this action, but when it merged for example:

```yaml
on:
  push:
    branches:
      - development
 ... 
  workflow_dispatch:
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ github.TOKEN }}
```

the workflow on the main branch does not trigger:

```yaml
on:
  push:
    branches:
      - main
  workflow_dispatch:

```
