### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by alagos** [devmasx/merge-branch#7]
Trying github actions for the 1st time here. 
My plans are to update any new pull request with last master changes:
```yml
on:
  pull_request:
    branches:
      - "release/**"
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge master -> release
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: ${{ github.ref }}
          github_token: ${{ github.token }}
```

but this it's throwing me:
```
/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/visfleet/test-merge-action/merges: 404 - Base does not exist // See: https://docs.github.com/rest/reference/repos#merge-a-branch (Octokit::NotFound)
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/response.rb:61:in `on_complete'
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
	from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/request/retry.rb:130:in `call'
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/bundle/gems/faraday-0.17.0/lib/faraday/connection.rb:175:in `post'
	from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
	from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/connection.rb:28:in `post'
	from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/client/commits.rb:214:in `merge'
	from /action/lib/index.rb:21:in `<main>'
```
My guessing is the problem comes from the access token, so I've tried using `github_token: ${{ secrets.GITHUB_TOKEN }}`, also adding:

```
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
but nothing seems to work. Any idea?
